package com.google.mlkit.md.classification

val ebayCategories = listOf(
    "Car",
    "Art",
    "Baby",
    "Books",
    "Business & Industrial",
    "Pen",
    "Cell Phones & Accessories",
    "Clothing, Shoes & Accessories",
    "Food",
    "Collectibles",
    "Computers/Tablets & Networking",
    "Consumer Electronics",
    "Crafts",
    "Dolls & Bears",
    "DVDs & Movies",
    "eBay Motors",
    "Entertainment Memorabilia",
    "Gift Cards & Coupons",
    "Health & Beauty",
    "Home & Garden",
    "Jewelry & Watches",
    "Music",
    "Musical Instruments & Gear",
    "Pet Supplies",
    "Pottery & Glass",
    "Real Estate",
    "Specialty Services",
    "Sporting Goods",
    "Sports Mem, Cards & Fan Shop",
    "Stamps",
    "Tickets & Experiences",
    "Toys & Hobbies",
    "Gym equipment",
    "Protein bar",
    "Travel",
    "Video Games & Consoles",
    "Everything Else",
    "Auto Parts & Accessories",
    "Cell Phones & Smartphones",
    "Tablets & eBook Readers",
    "Laptops & Netbooks",
    "Desktops & All-In-Ones",
    "Monitors, Projectors & Accs",
    "Printers, Scanners & Supplies",
    "Networking Equipment",
    "Video Game Consoles",
    "Video Games",
    "Consumer Electronics Accessories",
    "Surveillance & Smart Home",
    "Home Audio",
    "Portable Audio & Headphones",
    "Smart Watches & Wearables",
    "Kitchen & Dining",
    "Furniture",
    "Tools & Workshop Equipment",
    "Outdoor Power Equipment",
    "Lawn Mowers, Parts & Accs",
    "Yard, Garden & Outdoor Living",
    "Holiday & Seasonal Décor",
    "Home Improvement",
    "Electrical & Solar",
    "Heating, Cooling & Air",
    "Major Appliances",
    "Laptop",
    "Glass",
    "Monitor",
    "Keyboard",
    "Computer mouse",
    "Headphones",
    "Fashion Jewelry",
    "Fine Jewelry",
    "Loose Diamonds & Gemstones",
    "Art & Craft Supplies",
    "Sewing",
    "Home Arts & Crafts",
    "Collectible Coins",
    "Bullion",
    "Loose Beads",

    )
